### ISSUE TITLE
What is the difference between json_extract_scalar() and get_json_object()？

### ISSUE THREAD

**Issue by hanxuanliang** [aaronshan/hive-third-functions#13]
From the README, the two functions are not very different. What other advantages does json_extract_scalar() have?

**Comment by aaronshan** [comment]
`json_extract_scalar` function same with `get_json_object`，It returns only scalar values (Boolean, number, or string). It's not like to `json_extract` function( returns json value).

Example:
```
select json_extract("{\"a\":{\"b\":\"12\"}}", "$.a.b"); => "12"
select get_json_object("{\"a\":{\"b\":\"12\"}}", "$.a.b"); => 12
select json_extract_scalar("{\"a\":{\"b\":\"12\"}}", "$.a.b") => 12
```

**Comment by aaronshan** [comment]
> From the README, the two functions are not very different. What other advantages does json_extract_scalar() have?

 `json_extract_scalar` function same with `get_json_object`，It returns only scalar values (Boolean, number, or string). It's not like to `json_extract` function( returns json value).

Example:
```
select json_extract("{\"a\":{\"b\":\"12\"}}", "$.a.b"); => "12"
select get_json_object("{\"a\":{\"b\":\"12\"}}", "$.a.b"); => 12
select json_extract_scalar("{\"a\":{\"b\":\"12\"}}", "$.a.b") => 12
```
