### ISSUE TITLE
array_intersect bug

### ISSUE THREAD

**Issue by melin** [aaronshan/hive-third-functions#4]
array_intersect 有数组越界bug，代码也复杂，简化代码：
` @Override
    public Object evaluate(DeferredObject[] arguments) throws HiveException {
        Object leftArray = arguments[0].get();
        Object rightArray = arguments[1].get();

        int leftArrayLength = leftArrayOI.getListLength(leftArray);
        int rightArrayLength = rightArrayOI.getListLength(rightArray);

        // Check if array is null or empty
        if (leftArray == null || rightArray == null || leftArrayLength < 0 || rightArrayLength < 0) {
            return null;
        }

        if (leftArrayLength == 0) {
            return leftArray;
        }
        if (rightArrayLength == 0) {
            return rightArray;
        }

        List<?> leftList = leftArrayOI.getList(leftArray);
        List<?> rightList = leftArrayOI.getList(rightArray);
        HashSet<?> result_set = Sets.newHashSet(leftList);
        result_set.retainAll(rightList);

        return new ArrayList(result_set);
    }`

**Comment by aaronshan** [comment]
@melin 能给下触发数组越界bug的测试用例么？谢谢

**Comment by melin** [comment]
数据量比较大，没有确定是那条数据，就换掉实现代码了

**Comment by minhoryang** [comment]
There are 2 bugs:

1. If the duplicate value is located at the end of first array and the same value is stored multiple times in second array, [`leftPositions[++leftCurrentPosition]`](https://github.com/aaronshan/hive-third-functions/blob/master/src/main/java/cc/shanruifeng/functions/array/UDFArrayIntersect.java#L143-L155) raises ArrayIndexOutOfBoundsException.

`select array_intersect(array(0,1,2,3,4,5), array(1,1,2,2,5,5))`
`select array_intersect(array(0,1,2,3,4,4), array(1,1,2,2,3,4))`
```
java.lang.ArrayIndexOutOfBoundsException: 
      at cc.shanruifeng.functions.array.UDFArrayIntersect.evaluate(UDFArrayIntersect.java:147)
```
You can test this with INITIAL_SIZE = 1 (just set it smaller than input length)

2. [Value of `leftArrayElementTmp2` and `rightArrayElementTmp2` never changed](https://github.com/aaronshan/hive-third-functions/blob/master/src/main/java/cc/shanruifeng/functions/array/UDFArrayIntersect.java#L146-L155) even position changes. So ignoring rest of the values without comparing.

`select array_intersect(array(0,1,2,3,4,5), array(1,1,2,2,5,5))`
expected: <[1, 2, 5]>, but was: <[1]>

**Comment by aaronshan** [comment]
@minhoryang Thank you very much! It had been resolved!

**Comment by cceazj** [comment]
https://github.com/aaronshan/hive-third-functions/blame/f98fef86d328882c85ea40b69b14375d90d44201/src/main/java/com/github/aaronshan/functions/array/UDFArrayIntersect.java#L160
代码compare方法逻辑错误：位置数组写死了leftPositions。参数中应增加int[] positions，传递进来leftPositions或者rightPositions，相应方法调用处也需一并修改

**Comment by aaronshan** [comment]
> https://github.com/aaronshan/hive-third-functions/blame/f98fef86d328882c85ea40b69b14375d90d44201/src/main/java/com/github/aaronshan/functions/array/UDFArrayIntersect.java#L160 代码compare方法逻辑错误：位置数组写死了leftPositions。参数中应增加int[] positions，传递进来leftPositions或者rightPositions，相应方法调用处也需一并修改

@cceazj 能帮忙修复并提个PR吗？
