### ISSUE TITLE
UDFRe2JRegexpExtractAll参数个数判断和函数返回值不对

### ISSUE THREAD

**Issue by jinpeng123456** [aaronshan/hive-third-functions#6]
参数判断
`if (arguments.length != 2 || arguments.length != 3)`  
改成
`if (arguments.length != 2 && arguments.length != 3) `

返回值  
`list.add(searchedGroup.toString());` 
改成
`list.add(searchedGroup.toStringUtf8());`

**Comment by aaronshan** [comment]
@jinpeng123456 非常感谢。这个在2.2.1分支已经修复，稍后会合并到master

**Comment by jinpeng123456** [comment]
我修改了一些代码的bug，可以提交到一个分支吗？



在 2019-02-20 11:36:52，"aaron" <notifications@github.com> 写道：


@jinpeng123456 非常感谢。这个在2.2.1分支已经修复，稍后会合并到master

**Comment by aaronshan** [comment]
@jinpeng123456 可以的。欢迎参与~

**Comment by jinpeng123456** [comment]
我是不是没有权限push代码？可以开一个分支权限吗？





在 2019-02-21 16:36:57，"aaron" <notifications@github.com> 写道：


@jinpeng123456 可以的。欢迎参与~

**Comment by aaronshan** [comment]
@jinpeng123456 你可以fork一份代码到你的空间。然后在上面开发，之后发起Pull requests合并进来即可。可以参考：[github的多人协作](https://gist.github.com/suziewong/4378619)。欢迎并感谢你的参与~
